platform :ios, '9.0'

use_frameworks!


target 'PLPinViewController_Example' do
  pod 'PLPinViewController', :path => '../'
  pod 'Reveal-SDK', :configurations => ['Debug']
 
  target 'PLPinViewController_Tests' do
    inherit! :search_paths

    pod 'Expecta'
    pod 'OCMock'
    
  end
end
