use_frameworks!


target 'PLPinViewController_Example' do
  pod 'PLPinViewController', :path => '../'
  
  target 'PLPinViewController_Tests' do
    inherit! :search_paths

    pod 'Expecta'
    pod 'OCMock'
    
  end
end
